schema_version: 1

context:
  version: "1.4.3"

package:
  name: botsay
  version: ${{ version }}

source:
  url: https://github.com/xyproto/botsay/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 76edf0115d9659af71497363684513740c9c71cc1b54f05a4c7ac3a3eda20a65

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - botsay --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Output text together with randomly generated ASCII robots in colors inspired by synthwave/rainbows
  homepage: https://github.com/xyproto/botsay
  repository: https://github.com/xyproto/botsay

extra:
  recipe-maintainers:
    - danielnachun
